export const APP_NAVIGATOR = "APP_NAVIGATOR"
export const LOGIN_PAGE = "LOGIN_PAGE"

export const HOME_PAGE = "HOME_PAGE"
export const PROFILE_PAGE = "PROFILE_PAGE"

export const IMAGE_BROWSER_PAGE = "IMAGE_BROWSER_PAGE"
export const VIEW_IMAGE_PAGE = "VIEW_IMAGE_PAGE"

export const VIDEO_PAGE = 'VIDEO_PAGE'
export const AUDIO_PAGE = 'AUDIO_PAGE'

export const NOISOI_TAI = "NOISOI_TAI"
export const NOISOI_TAI_FILTER = "NOISOI_TAI_FILTER"
export const NOISOI_TAI_DETAIL = "NOISOI_TAI_DETAIL"
export const NOISOI_TAI_CREATE = "NOISOI_TAI_CREATE"

export const NOISOI_MUI = "NOISOI_MUI"
export const NOISOI_MUI_FILTER = "NOISOI_MUI_FILTER"
export const NOISOI_MUI_DETAIL = "NOISOI_MUI_DETAIL"
export const NOISOI_MUI_CREATE = "NOISOI_MUI_CREATE"

export const NOISOI_HONG = "NOISOI_HONG"
export const NOISOI_HONG_FILTER = "NOISOI_HONG_FILTER"
export const NOISOI_HONG_DETAIL = "NOISOI_HONG_DETAIL"
export const NOISOI_HONG_CREATE = "NOISOI_HONG_CREATE"

export const SOI_DA = "SOI_DA"
export const SOI_DA_FILTER = "SOI_DA_FILTER"
export const SOI_DA_DETAIL = "SOI_DA_DETAIL"
export const SOI_DA_CREATE = "SOI_DA_CREATE"

export const NGHE_PHOI = "NGHE_PHOI"
export const NGHE_PHOI_FILTER = "NGHE_PHOI_FILTER"
export const NGHE_PHOI_DETAIL = "NGHE_PHOI_DETAIL"
export const NGHE_PHOI_CREATE = "NGHE_PHOI_CREATE"

export const UPLOAD_PAGE = "UPLOAD_PAGE"
export const QUAN_LY_DU_LIEU = "QUAN_LY_DU_LIEU"
export const DU_LIEU_DETAIL = "DU_LIEU_DETAIL"